version: '3'

services:
  users:
    build: .
    image: ride:latest
    container_name: rides
    command: python rides.py
    restart: always
    environment:
    - TEAM_NAME=CC_0188_1000_1324_1644
    ports:
        - "8000:8000"

 
